# Generated by Django 3.1.3 on 2020-11-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urania', '0002_auto_20201118_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='current_words',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
