# Generated by Django 3.1.3 on 2020-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urania', '0003_voter_current_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='current_words',
            field=models.JSONField(default=dict),
        ),
    ]
