# Generated by Django 3.1.3 on 2020-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urania', '0004_auto_20201118_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='current_words',
            field=models.CharField(max_length=1024),
        ),
    ]
